// Generated by CoffeeScript 1.11.1
(function() {
  var connect, gulp, server;

  gulp = require('gulp');

  server = require('gulp-server-livereload');

  connect = require('gulp-connect');

  gulp.task('webserver', function() {
    gulp.src('multi-vendor').pipe(server({
      livereload: true,
      directoryListing: true,
      open: true
    }));
  });

  gulp.task('default', ['webserver']);

}).call(this);
